=== ivn-maria/University-Projects/XMLCatalog_HotelCatalog/src/main/resources/hotelCatalog.dtd
<!ELEMENT hotelCatalog (hotel+, hotelChain+, region+)>

<!ELEMENT hotel (name, address, description, photos, features, rooms)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT features (#PCDATA)>
<!ATTLIST hotel hotelChainID IDREF #REQUIRED>
<!ATTLIST hotel regionID IDREF #REQUIRED>
<!ATTLIST hotel type (Conference|Resort|Botique) #REQUIRED>
<!ATTLIST hotel stars (1|2|3|4|5) #REQUIRED>

<!ELEMENT photos (photo*)>
<!ELEMENT photo EMPTY>
<!ATTLIST photo src ENTITY #REQUIRED>

<!ELEMENT rooms (room+)>
<!ELEMENT room (price, capacity)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT capacity (#PCDATA)>
<!ATTLIST room type (single|double|suite) #REQUIRED>

<!ELEMENT hotelChain (name, description, numberOfHotels)>
<!ELEMENT numberOfHotels (#PCDATA)>
<!ATTLIST hotelChain hotelChainID ID #REQUIRED>

<!ELEMENT region (name, description, sights?, transports?)>
<!ATTLIST region regionID ID #REQUIRED>

<!ELEMENT sights (#PCDATA)>

<!ELEMENT transports (transport+)>
<!ELEMENT transport (name, link)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST transport type (busStation|trainStation|airport|publicTransport) #REQUIRED>

=== ivn-maria/University-Projects/XMLCatalog_HotelCatalog/src/main/resources/hotelCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hotelCatalog.xsl"?>
<!DOCTYPE hotelCatalog SYSTEM "hotelCatalog.dtd" [
    <!NOTATION PNG SYSTEM "image/png">
    <!NOTATION JPG SYSTEM "image/jpeg">
	<!ENTITY festa_sofia_hotel SYSTEM "images/Festa_sofia_hotel.jpg" NDATA JPG>
	<!ENTITY festa_sofia_room SYSTEM "images/Festa_sofia_room.jpg" NDATA JPG>
	<!ENTITY festa_borovets_hotel SYSTEM "images/Festa_borovets_hotel.jpg" NDATA JPG>
	<!ENTITY festa_borovets_room SYSTEM "images/Festa_borovets_room.jpg" NDATA JPG>
	<!ENTITY royal_castle_hotel SYSTEM "images/Royal_castle_hotel.jpg" NDATA JPG>
	<!ENTITY royal_castle_room SYSTEM "images/Royal_castle_room.jpg" NDATA JPG>
	<!ENTITY marinela_hotel SYSTEM "images/Marinela-hotel.jpg" NDATA JPG>
	<!ENTITY marinela_room SYSTEM "images/Marinela-room.jpg"  NDATA JPG>
	<!ENTITY chaika_hotel SYSTEM "images/Chaika_hotel.png"  NDATA PNG>
	<!ENTITY chaika_room SYSTEM "images/Chaika_room.jpg" NDATA JPG>
	<!ENTITY rila_borovets_hotel SYSTEM "images/Rila_borovets_hotel.jpg" NDATA JPG>
	<!ENTITY rila_borovets_room SYSTEM "images/Rila_borovets_room.jpg" NDATA JPG>
	<!ENTITY perla_beach_hotel SYSTEM "images/Perla_beach_hotel.jpg" NDATA JPG>
	<!ENTITY perla_beach_room SYSTEM "images/Perla_beach_room.jpg" NDATA JPG>
]>

<hotelCatalog>

 <hotel hotelChainID="Festa" regionID="SOF" type="Conference" stars="4">
  <name>Festa Sofia</name>
  <address>Bulgaria Blvd. 83, 1404 Manastirski Livadi, Sofia</address>
  <description>
   Located 200 meters from Mall Bulgaria and the tram stop, Festa Sofia hotel offers elegant rooms with free Wi-Fi and satellite TV.
   It features a wellness center and beauty salon, as well as 2 restaurants, 3 bars, and 4 conference halls. The spa center includes a sauna and steam bath.
   Guests can stay fit in the fitness center or enjoy massage and aromatherapy treatments. There is also a hair salon on site. 
   Restaurant Festa serves local and international cuisine in a secluded atmosphere. The Mezzanine bar offers sophisticated drinks and desserts.
   The lobby bar serves a variety of coffee specialties. Sahara Hookah Bar offers its guests exquisite varieties of tobacco and a wonderful selection of drinks.
   All rooms at Festa Sofia hotel have a panoramic view of the city or Vitosha. They are equipped with air conditioning and a safe. 
   The private bathrooms have a bathtub. The hotel is located in a modern business area, 18 km from Sofia International Airport and 5 km from the city center.
  </description>
  <photos>
   <photo src="festa_sofia_hotel" />
   <photo src="festa_sofia_room" />
  </photos>
  <features>
   Private Parking, Free WiFi, Airport Shuttle, Fitness Center, Family Rooms, Non-Smoking Rooms, 2 Restaurants,
   24-Hour Reception, Bar, Good Breakfast
  </features>
  <rooms>
   <room type="single">
	<price>120</price>
	<capacity>1</capacity>
   </room>
   <room type="double">
	<price>150</price>
	<capacity>2</capacity>
   </room>
   <room type="suite">
	<price>200</price>
	<capacity>3</capacity>
   </room>
  </rooms>
 </hotel>

 <hotel hotelChainID="Festa" regionID="BOR" type="Botique" stars="5">
  <name>Festa Winter Borovets</name>
  <address>2010 Borovets, Borovets</address>
  <description>
   The luxurious 5-star Festa Winter Palace is located at the foot of Rila in Borovets, just 100 meters from the ski slopes and the gondola lift. 
   It offers an indoor pool. The large relaxation center with a pool, sauna, steam bath, fitness facilities, and a wide range of massages is a wonderful place 
   to relax after a day outdoors in the mountains. The spacious rooms and suites feature antique-style furniture, and a balcony overlooking the mountain.
   The hotel has 2 restaurants and 2 bars serving gourmet cuisine and select drinks. Free WiFi is available throughout Festa Winter Palace.
  </description>
  <photos>
   <photo src="festa_borovets_hotel" />
   <photo src="festa_borovets_room" />
  </photos>
  <features>
   Indoor Pool, Private Parking, Free WiFi, Family Rooms, Fitness Center, Restaurant, Ski Services, Coffee/Tea Maker in All Rooms,
   Bar, Good Breakfast
  </features>
  <rooms>
   <room type="single">
	<price>600</price>
	<capacity>1</capacity>
   </room>
   <room type="double">
	<price>650</price>
	<capacity>2</capacity>
   </room>
   <room type="suite">
	<price>1100</price>
	<capacity>3</capacity>
   </room>
  </rooms>
 </hotel>

 <hotel hotelChainID="Vic" regionID="BRG" type="Resort" stars="5">
  <name>Royal Castle Design &amp; SPA</name>
  <address>8259 Elenite, Bulgaria</address>
  <description>
   Royal Castle Design &amp; SPA is located in a closed and peaceful complex in the resort village of Elenite. The hotel offers an outdoor seasonal pool with free sun loungers
   and umbrellas, as well as access to the beach. During the summer season, the hotel hosts various live shows, concerts, and parties with DJs. The hotel offers elegant 
   designer rooms, all equipped with a flat-screen TV, minibar, and a private balcony. Guests also have access to 4 VIP apartments with boutique designer furnishings, 
   their own SPA area, and additional amenities for a truly luxurious experience. During the summer season, hotel guests have free access to the "Atlantis" aqua park. 
   Available for guests are an indoor pool, sauna, SPA center, as well as a fitness room and a squash court.
  </description>
  <photos>
   <photo src="royal_castle_hotel" />
   <photo src="royal_castle_room" />
  </photos>
  <features>
   Sea View, Outdoor and Indoor Pool, Private Parking, Free WiFi, 24-Hour Reception, Fitness Center, 2 Restaurants,
   Spa and Wellness, Family Rooms, Bar, Good Breakfast
  </features>
   <rooms>
	<room type="double">
	 <price>475</price>
	 <capacity>2</capacity>
	</room>
	<room type="suite">
	 <price>1050</price>
	 <capacity>4</capacity>
	</room>
   </rooms>
  </hotel>

 <hotel hotelChainID="Vic" regionID="SOF" type="Conference" stars="5">
  <name>Hotel Marinela Sofia</name>
  <address>James Bourchier Blvd. 100, Lozenets, 1407 Sofia</address>
  <description>
    Hotel Marinela Sofia has an entirely new design and is located 20 minutes by car from Sofia Airport. It offers an indoor pool, 6 restaurants, 4 bars, a fitness club,
	and a picturesque view of the city and the mountain. The unique Japanese garden is a wonderful place for relaxation or meetings. Guests can dine at the Panorama restaurant 
	while enjoying the city view and spend a great evening at the Megami club. The hotel has a large ballroom and a conference hall, plus 13 meeting rooms and a remarkable 
	top-floor hall at Hotel Marinela with a unique view of Sofia. Each room is equipped with air conditioning, heating system, flat-screen TV, free WiFi, and a modern 
	entertainment system with video and music.
  </description>
  <photos>
   <photo src="marinela_hotel" />
   <photo src="marinela_room" />
  </photos>
  <features>
   Airport Transfer, Private Parking, Indoor Pool, Free WiFi, Mountain View, 6 Restaurants, Spa and Wellness,
   Family Rooms, Bar, Good Breakfast
  </features>
  <rooms>
   <room type="single">
    <price>175</price>
    <capacity>1</capacity>
   </room>
   <room type="double">
    <price>230</price>
    <capacity>2</capacity>
   </room>
   <room type="suite">
    <price>2200</price>
    <capacity>4</capacity>
   </room>
  </rooms>
 </hotel>

 <hotel hotelChainID="Vic" regionID="BRG" type="Resort" stars="3">
  <name>Chaika Beach Resort</name>
  <address>Sunny Beach, 8240 Sunny Beach</address>
  <description>
   Chaika Beach Resort is located in the northern part of Sunny Beach, right on the beachfront. It is divided into three buildings, some of which offer a panoramic view of the sea.
   The hotel has direct access to the beach, 2 outdoor pools, and several restaurants and bars. All-inclusive light offers include a main restaurant with a variety of 
   delicious dishes, a lobby bar, and a pool bar with umbrellas and sun loungers. Guests can enjoy top-notch summer cocktails or beer at the Irish Bar. All rooms are equipped 
   with air conditioning, a TV, and free WiFi.
  </description>
  <photos>
   <photo src="chaika_hotel" />
   <photo src="chaika_room" />
  </photos>
  <features>
   Sea View, Private Parking, 2 Pools, Free WiFi, Large Outdoor Garden, Restaurant, Bar, Family Rooms,
   24-Hour Reception, Good Breakfast
  </features>
  <rooms>
   <room type="double">
    <price>150</price>
    <capacity>2</capacity>
   </room>
   <room type="suite">
    <price>200</price>
    <capacity>4</capacity>
   </room>
  </rooms>
 </hotel>

 <hotel hotelChainID="BT" regionID="BOR" type="Resort" stars="4">
  <name>Hotel Rila Borovets</name>
  <address>Borovets, 2010 Borovets</address>
  <description>
   Rila Hotel Borovets is located in the heart of the first mountain resort in the Balkans - Borovets, 70 km away from Sofia. Rila Hotel Borovets is situated at the end of
   the ski slopes, just 200 meters from the gondola lift. It offers a SPA center, various restaurants, and entertainment clubs. Private parking and free WiFi are provided.
   The conference center offers different options for organizing business and personal events. Guests can take advantage of free access to the SPA center, 
   which includes a 25-meter swimming pool, 2 hydro-massage tubs, a fitness center, thermal zones, and relaxation areas. The hotel offers relaxation opportunities 
   through outdoor and indoor sports and entertainment activities. Equipment rental and skiing or snowboarding lessons are also available.
  </description>
  <photos>
   <photo src="rila_borovets_hotel" />
   <photo src="rila_borovets_room" />
  </photos>
  <features>
   Mountain View, Private Parking, Indoor Pool, Close to Ski Slopes, Airport Transfer, 3 Restaurants, Bar,
   Family Rooms, Spa and Wellness Center, Fitness Center
  </features>
  <rooms>
   <room type="single">
    <price>300</price>
    <capacity>1</capacity>
   </room>
   <room type="double">
    <price>330</price>
